function [ Cout, Bmag ] = nlcon_Bmin( Bxyz, Bmin, Bmag )
% nlcon_Bmin - calculates whether mean ROI field meets min field constraint
%
% Inputs:
%   Bxyz - field vector, in form generated by Dipole matrix (ie.
%           Bxyz(1:3) = [Bx1, By1, Bz1]; Bxyz(4:6) = [Bx2, By2, Bz2], etc)
%   Bmin - minimum allowable mean ROI field, in units of [T]
%   Bmag (optional) - magnitude of B at each point
%
% Outputs:
%   Cout - binary scalar specifying if constraint is met
%           1==Field meets constraint (mean({|B|})>=Bmin
%           0==Constraint not met (mean({|B|})<Bmin)
%
    if nargin<3
        Bmag = sqrt((Bxyz(1:3:end).^2 + Bxyz(2:3:end).^2 + Bxyz(3:3:end).^2));
    end
    
    Cout = Bmin - mean( Bmag ) ;


end

