function [ hands ] = dispBvec_Lumb( bvec, ROImsk_or, plottype, plane, hands )
% dispBvec - display magnetic field in ROI given input field vector
%
%   Inputs:
%     bvec      - B-field arranged in vector format generated by dipole
%                   matrix
%     ROImsk_or - 3D cartesian ROI mask for target region
%     plottype  - value=='mag' (to plot |B|) or 'xyz' (to plot Bx, By, and
%                   Bz). Any other value defaults to 'mag' plot
%     plane     - value=='XY' (to plot in XY plane), 'XZ' (to plot in XZ
%                   plane), or 'YZ' (to plot in YZ plane). Other values
%                   default to 'XZ'
%     hands     - (optional) set of figure numbers to use

    if nargin<3
        plottype = 'mag';
    end
    if nargin<4
        plane = 'XZ';
    end
    if nargin<5
        switch plottype
            case 'mag'
                hands = figure;
            case 'xyz'
                hands(1) = figure;
                hands(2) = figure;
                hands(3) = figure;
            otherwise
                hands = figure;
        end
    end

    [ Bx By Bz ] = vec2field( bvec );
    
    Bm = sqrt( Bx.^2 + By.^2 + Bz.^2 );

    Bx_mat = zeros(size( ROImsk_or ));
    By_mat = zeros(size( ROImsk_or ));
    Bz_mat = zeros(size( ROImsk_or ));

    Bx_mat(ROImsk_or) = Bx;
    By_mat(ROImsk_or) = By;
    Bz_mat(ROImsk_or) = Bz;

    Bm_mat = sqrt( Bx_mat.^2 + By_mat.^2 + Bz_mat.^2 );
    switch plane
        case 'XY'
            pmat = [1 2 3];
        case 'XZ'
            pmat = [3 1 2];
        case 'YZ'
            pmat = [2 3 1];
        otherwise
            pmat = [1 2 3];
    end
    

    switch plottype
        case 'mag'
            mosaic(permute( Bm_mat, pmat) , 3, 3, hands); colormap jet; colorbar; caxis([min(Bm(:)) max(Bm(:))]);
        case 'xyz'
            mosaic(permute( Bx_mat, pmat), 3, 3, hands(1)); colormap jet; colorbar
            mosaic(permute( By_mat, pmat), 3, 3, hands(2)); colormap jet; colorbar
            mosaic(permute( Bz_mat, pmat), 3, 3, hands(3)); colormap jet; colorbar
        otherwise
            mosaic(permute( Bm_mat, pmat), 3, 3, hands); colormap jet; colorbar
    end
    
end

